import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ActionSheet, BusyIndicator, Button, Dialog, Icon, Label, Link, MessageStrip, ObjectStatus, Option, Select, Table, TableCell, TableHeaderCell, TableHeaderRow, TableRow, Title } from "@ui5/webcomponents-react";
import { PersianDatePicker, type PersianDateDraftState } from "@/shared/components/PersianDatePicker";
import { ModalDialogHeader } from "@/shared/components/ModalDialogHeader";
import { formatPersianDate } from "@/shared/utils/date.utils";

export type CoverageLifecycle = "ACTIVE" | "INACTIVE" | "DELETED";
export type CoverageEditState = "FINAL" | "DRAFT_NEW" | "DRAFT_EDITED" | "DRAFT_PENDING_DELETE";
export interface CoverageOption { id: string; code: string; title: string; status: CoverageLifecycle; validFrom: string | null; validTo: string | null; }
export interface CoverageRow {
  id: string | null; subprocessId: string; subprocessCode: string; subprocessTitle: string;
  leftScopeId: string; leftId: string; leftCode: string; leftTitle: string; leftScopeStatus: CoverageLifecycle; leftScopeValidFrom: string | null; leftScopeValidTo: string | null;
  rightScopeId: string; rightId: string; rightCode: string; rightTitle: string; rightScopeStatus: CoverageLifecycle; rightScopeValidFrom: string | null; rightScopeValidTo: string | null;
  status: CoverageLifecycle; validFrom: string | null; validTo: string | null; version: number | null;
  editState: CoverageEditState; original: CoverageRow | null;
}
export interface NormalizedCoverageChange { operation: "CREATE_OR_RESTORE" | "UPDATE" | "ACTIVATE" | "INACTIVATE" | "DELETE" | "RESTORE"; leftScopeId: string; rightScopeId: string; coverageId?: string; version?: number; validFrom?: string | null; validTo?: string | null; requestedStatus?: "ACTIVE" | "INACTIVE"; }
export interface TypedCoverageDraftState { changes: NormalizedCoverageChange[]; dirty: boolean; ready: boolean; invalid: boolean; }

interface Texts { title: string; empty: string; savedScopesFirst: string; add: string; edit: string; remove: string; undo: string; activate: string; inactivate: string; restore: string; left: string; right: string; lifecycle: string; validFrom: string; validTo: string; active: string; inactive: string; deleted: string; draft: string; save: string; cancel: string; actions: string; invalidDate: string; duplicate: string; loadError: string; }
interface Props { subprocessId: string | null; readOnly: boolean; busy?: boolean; canMutate: boolean; texts: Texts; load: (subprocessId: string, signal: AbortSignal) => Promise<{ rows: CoverageRow[]; deleted: CoverageRow[]; left: CoverageOption[]; right: CoverageOption[] }>; leftHref?: (id: string) => string; rightHref?: (id: string) => string; onDraftStateChange?: (state: TypedCoverageDraftState) => void; }

function toChanges(rows: CoverageRow[]): NormalizedCoverageChange[] {
  return rows.flatMap((row): NormalizedCoverageChange[] => {
    if (row.editState === "DRAFT_PENDING_DELETE" && row.id && row.version != null) return [{ operation: "DELETE", leftScopeId: row.leftScopeId, rightScopeId: row.rightScopeId, coverageId: row.id, version: row.version }];
    if (row.editState === "DRAFT_NEW" || row.original?.status === "DELETED") return [{ operation: "CREATE_OR_RESTORE", leftScopeId: row.leftScopeId, rightScopeId: row.rightScopeId, validFrom: row.validFrom, validTo: row.validTo }];
    if (row.editState !== "DRAFT_EDITED" || !row.id || row.version == null || !row.original) return [];
    const datesChanged = row.validFrom !== row.original.validFrom || row.validTo !== row.original.validTo;
    if (datesChanged) return [{ operation: "UPDATE", leftScopeId: row.leftScopeId, rightScopeId: row.rightScopeId, coverageId: row.id, version: row.version, validFrom: row.validFrom, validTo: row.validTo, requestedStatus: row.status === "DELETED" ? undefined : row.status }];
    if (row.status !== row.original.status) return [{ operation: row.status === "ACTIVE" ? "ACTIVATE" : "INACTIVATE", leftScopeId: row.leftScopeId, rightScopeId: row.rightScopeId, coverageId: row.id, version: row.version }];
    return [];
  });
}
function same(row: CoverageRow, original: CoverageRow) { return row.status === original.status && row.validFrom === original.validFrom && row.validTo === original.validTo; }
function ownClose(event: unknown) { const e=event as {target?:EventTarget|null;currentTarget?:EventTarget|null}; return Boolean(e.target&&e.currentTarget&&e.target===e.currentTarget); }

export function TypedCoverageSection({ subprocessId, readOnly, busy=false, canMutate, texts, load, leftHref, rightHref, onDraftStateChange }: Props) {
  const [rows,setRows]=useState<CoverageRow[]>([]); const [deleted,setDeleted]=useState<CoverageRow[]>([]); const [left,setLeft]=useState<CoverageOption[]>([]); const [right,setRight]=useState<CoverageOption[]>([]); const [loading,setLoading]=useState(Boolean(subprocessId)); const [loaded,setLoaded]=useState(!subprocessId); const [error,setError]=useState<string|null>(null);
  const [dialog,setDialog]=useState<{mode:"add"|"edit";key:string|null}|null>(null); const [leftId,setLeftId]=useState(""); const [rightId,setRightId]=useState(""); const [validFrom,setValidFrom]=useState<string|null>(null); const [validTo,setValidTo]=useState<string|null>(null); const [dateDrafts,setDateDrafts]=useState<Record<"from"|"to",PersianDateDraftState>>({from:{draftValue:"",valid:true,dirty:false},to:{draftValue:"",valid:true,dirty:false}}); const [actionKey,setActionKey]=useState<string|null>(null); const [opener,setOpener]=useState<HTMLElement|null>(null); const generation=useRef(0);
  const reload=useCallback(async()=>{if(!subprocessId){setRows([]);setDeleted([]);setLeft([]);setRight([]);setLoaded(true);setLoading(false);return;}const current=++generation.current;const controller=new AbortController();setLoading(true);try{const data=await load(subprocessId,controller.signal);if(current!==generation.current)return;setRows(data.rows);setDeleted(data.deleted);setLeft(data.left);setRight(data.right);setLoaded(true);setError(null);}catch(e){if(e instanceof Error&&e.name==="AbortError")return;if(current===generation.current){setError(texts.loadError);setLoaded(false);}}finally{if(current===generation.current)setLoading(false);}return()=>controller.abort();},[load,subprocessId,texts.loadError]);
  useEffect(()=>{void reload();return()=>{generation.current+=1;}},[reload]);
  const changes=useMemo(()=>toChanges(rows),[rows]); const invalid=!dateDrafts.from.valid||!dateDrafts.to.valid||(Boolean(validFrom&&validTo&&validTo<validFrom));
  useEffect(()=>onDraftStateChange?.({changes,dirty:changes.length>0,ready:loaded&&!loading,invalid:Boolean(error)||invalid}),[changes,error,invalid,loaded,loading,onDraftStateChange]);
  const visible=rows.filter(r=>r.status!=="DELETED"); const action=actionKey?rows.find(r=>`${r.id??"new"}:${r.leftScopeId}:${r.rightScopeId}`===actionKey)??null:null;
  const openAdd=()=>{setDialog({mode:"add",key:null});setLeftId("");setRightId("");setValidFrom(null);setValidTo(null);};
  const openEdit=(row:CoverageRow)=>{setDialog({mode:"edit",key:`${row.id??"new"}:${row.leftScopeId}:${row.rightScopeId}`});setLeftId(row.leftScopeId);setRightId(row.rightScopeId);setValidFrom(row.validFrom);setValidTo(row.validTo);};
  const closeDialog=()=>{setDialog(null);setDateDrafts({from:{draftValue:"",valid:true,dirty:false},to:{draftValue:"",valid:true,dirty:false}});};
  const saveDialog=()=>{if(!dialog||!leftId||!rightId||invalid)return;const key=dialog.key;if(dialog.mode==="edit"&&key){setRows(current=>current.map(row=>{const rowKey=`${row.id??"new"}:${row.leftScopeId}:${row.rightScopeId}`;if(rowKey!==key)return row;const next={...row,validFrom,validTo};return {...next,editState:next.original&&same(next,next.original)?"FINAL":"DRAFT_EDITED"};}));closeDialog();return;}if(rows.some(row=>row.status!=="DELETED"&&row.leftScopeId===leftId&&row.rightScopeId===rightId)){setError(texts.duplicate);return;}const l=left.find(x=>x.id===leftId);const r=right.find(x=>x.id===rightId);if(!l||!r)return;const restored=deleted.find(x=>x.leftScopeId===leftId&&x.rightScopeId===rightId);const next:CoverageRow={id:restored?.id??null,subprocessId:subprocessId??"",subprocessCode:restored?.subprocessCode??"",subprocessTitle:restored?.subprocessTitle??"",leftScopeId:leftId,leftId:restored?.leftId??leftId,leftCode:l.code,leftTitle:l.title,leftScopeStatus:l.status,leftScopeValidFrom:l.validFrom,leftScopeValidTo:l.validTo,rightScopeId:rightId,rightId:restored?.rightId??rightId,rightCode:r.code,rightTitle:r.title,rightScopeStatus:r.status,rightScopeValidFrom:r.validFrom,rightScopeValidTo:r.validTo,status:"ACTIVE",validFrom,validTo,version:restored?.version??null,editState:"DRAFT_NEW",original:restored??null};setRows(current=>[...current,next]);closeDialog();};
  const mutate=(row:CoverageRow, status:"ACTIVE"|"INACTIVE")=>setRows(current=>current.map(x=>x===row?{...x,status,editState:x.original&&same({...x,status},x.original)?"FINAL":"DRAFT_EDITED"}:x));
  const remove=(row:CoverageRow)=>setRows(current=>row.id?current.map(x=>x===row?{...x,editState:"DRAFT_PENDING_DELETE"}:x):current.filter(x=>x!==row)); const undo=(row:CoverageRow)=>setRows(current=>row.original?current.map(x=>x===row?{...row.original!,original:row.original,editState:"FINAL"}:x):current.filter(x=>x!==row));
  const closeActions=()=>{setActionKey(null);setOpener(null);}; const statusText=(row:CoverageRow)=>row.editState==="DRAFT_PENDING_DELETE"?texts.deleted:row.editState!=="FINAL"?texts.draft:row.status==="ACTIVE"?texts.active:texts.inactive;
  if(!subprocessId)return <MessageStrip design="Information">{texts.savedScopesFirst}</MessageStrip>;
  return <section className="typedCoverageSection"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"1rem",marginBlock:"1rem"}}><Title level="H5">{texts.title}</Title>{!readOnly&&canMutate?<Button design="Emphasized" icon="add" disabled={busy||loading} onClick={openAdd}>{texts.add}</Button>:null}</div>{error?<MessageStrip design="Negative" onClose={()=>setError(null)}>{error}</MessageStrip>:null}{loading?<BusyIndicator active delay={0}/>:visible.length?<Table headerRow={<TableHeaderRow><TableHeaderCell>{texts.left}</TableHeaderCell><TableHeaderCell>{texts.right}</TableHeaderCell><TableHeaderCell>{texts.validFrom}</TableHeaderCell><TableHeaderCell>{texts.validTo}</TableHeaderCell><TableHeaderCell>{texts.lifecycle}</TableHeaderCell>{!readOnly?<TableHeaderCell>{texts.actions}</TableHeaderCell>:null}</TableHeaderRow>}>{visible.map(row=>{const key=`${row.id??"new"}:${row.leftScopeId}:${row.rightScopeId}`;return <TableRow key={key}><TableCell><Link href={leftHref?.(row.leftId)}>{`${row.leftCode} - ${row.leftTitle}`}</Link><ObjectStatus state={row.leftScopeStatus==="ACTIVE"?"Positive":"None"}>{row.leftScopeStatus==="ACTIVE"?texts.active:texts.inactive}</ObjectStatus></TableCell><TableCell><Link href={rightHref?.(row.rightId)}>{`${row.rightCode} - ${row.rightTitle}`}</Link><ObjectStatus state={row.rightScopeStatus==="ACTIVE"?"Positive":"None"}>{row.rightScopeStatus==="ACTIVE"?texts.active:texts.inactive}</ObjectStatus></TableCell><TableCell>{formatPersianDate(row.validFrom)}</TableCell><TableCell>{formatPersianDate(row.validTo)}</TableCell><TableCell><ObjectStatus state={row.editState==="FINAL"&&row.status==="ACTIVE"?"Positive":"Information"} icon={<Icon name={row.editState==="FINAL"?"accept":"edit"} mode="Decorative"/>}>{statusText(row)}</ObjectStatus></TableCell>{!readOnly?<TableCell><Button design="Transparent" icon="overflow" accessibleName={texts.actions} onClick={e=>{setActionKey(key);setOpener(e.currentTarget as HTMLElement);}}/></TableCell>:null}</TableRow>})}</Table>:loaded?<div>{texts.empty}</div>:null}
    {!readOnly?<ActionSheet open={Boolean(action&&opener)} opener={opener} onClose={closeActions}>{action?.editState!=="FINAL"?<Button icon="undo" onClick={()=>{closeActions();undo(action!);}}>{texts.undo}</Button>:<>{action?<Button icon="edit" onClick={()=>{closeActions();openEdit(action);}}>{texts.edit}</Button>:null}{action?.status==="ACTIVE"?<Button icon="pause" onClick={()=>{closeActions();mutate(action!,"INACTIVE");}}>{texts.inactivate}</Button>:action?<Button icon="accept" onClick={()=>{closeActions();mutate(action,"ACTIVE");}}>{texts.activate}</Button>:null}{action?<Button icon="delete" onClick={()=>{closeActions();remove(action);}}>{texts.remove}</Button>:null}</>}</ActionSheet>:null}
    <Dialog open={Boolean(dialog)} onClose={e=>{if(ownClose(e))closeDialog();}}><ModalDialogHeader title={dialog?.mode==="add"?texts.add:texts.edit} onClose={closeDialog}/><div style={{display:"grid",gap:"1rem",padding:"1rem",minWidth:"min(36rem,80vw)"}}><Label showColon>{texts.left}</Label><Select value={leftId} disabled={dialog?.mode==="edit"} onChange={e=>setLeftId(e.detail.selectedOption?.value??"")}><Option value="">-</Option>{left.filter(x=>x.status==="ACTIVE").map(x=><Option key={x.id} value={x.id}>{`${x.code} - ${x.title}`}</Option>)}</Select><Label showColon>{texts.right}</Label><Select value={rightId} disabled={dialog?.mode==="edit"} onChange={e=>setRightId(e.detail.selectedOption?.value??"")}><Option value="">-</Option>{right.filter(x=>x.status==="ACTIVE").map(x=><Option key={x.id} value={x.id}>{`${x.code} - ${x.title}`}</Option>)}</Select><Label showColon>{texts.validFrom}</Label><PersianDatePicker value={validFrom??""} accessibleName={texts.validFrom} onChange={v=>setValidFrom(v||null)} invalidValueMessage={texts.invalidDate} onDraftStateChange={s=>setDateDrafts(c=>({...c,from:s}))}/><Label showColon>{texts.validTo}</Label><PersianDatePicker value={validTo??""} accessibleName={texts.validTo} onChange={v=>setValidTo(v||null)} invalidValueMessage={texts.invalidDate} onDraftStateChange={s=>setDateDrafts(c=>({...c,to:s}))}/><div style={{display:"flex",justifyContent:"flex-end",gap:".5rem"}}><Button onClick={closeDialog}>{texts.cancel}</Button><Button design="Emphasized" disabled={!leftId||!rightId||invalid} onClick={saveDialog}>{texts.save}</Button></div></div></Dialog>
  </section>;
}
