import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button, Input, MessageStrip, TextArea, Title } from "@ui5/webcomponents-react";
import { DocumentManager, EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE, toDocumentAggregateDraftError, toDocumentAggregateRequest, type DocumentAggregateDraftError, type ParentSaveDocumentDraftState } from "@/features/document";
import { centralCatalogApi } from "../infra/centralCatalog.api";
import PolicyVersionPanel from "./PolicyVersionPanel";
import { configByKind, familyConfigs } from "../config";
import type { CatalogFamily, CatalogForm, CatalogItem, CatalogKind } from "../domain/centralCatalog.model";
import { useCentralCatalogState } from "../state/centralCatalog.state";
import "./central-catalog.css";

const EMPTY_FORM: CatalogForm = { code: "", title: "", description: "", validFrom: "", validTo: "", sortOrder: "0", parentId: "" };
const valueOf = (event: unknown) => (event as { target?: { value?: string } }).target?.value ?? "";
function parentOf(item: CatalogItem, field?: string) { if (!field) return ""; return String((item as unknown as Record<string, unknown>)[field] ?? item.parentId ?? ""); }
function formOf(item?: CatalogItem | null, parentField?: string): CatalogForm { return item ? { code: item.code, title: item.title, description: item.description ?? "", validFrom: item.validFrom ?? "", validTo: item.validTo ?? "", sortOrder: String(item.sortOrder ?? 0), parentId: parentOf(item, parentField) } : { ...EMPTY_FORM }; }

export default function CentralCatalogPage({ family, initialKind }: { family: CatalogFamily; initialKind?: CatalogKind }) {
    const { t } = useTranslation(); const configs = useMemo(() => familyConfigs(family), [family]);
    const [kind, setKind] = useState<CatalogKind>(initialKind ?? configs[0].kind); const config = configByKind(kind);
    const items = useCentralCatalogState((state) => state.items); const parents = useCentralCatalogState((state) => state.parents); const selected = useCentralCatalogState((state) => state.selected);
    const loading = useCentralCatalogState((state) => state.loading); const error = useCentralCatalogState((state) => state.error); const loadCatalog = useCentralCatalogState((state) => state.load); const selectCatalog = useCentralCatalogState((state) => state.select); const clearSelection = useCentralCatalogState((state) => state.clearSelection); const setError = useCentralCatalogState((state) => state.setError); const resetCatalog = useCentralCatalogState((state) => state.reset);
    const [form, setForm] = useState<CatalogForm>({ ...EMPTY_FORM }); const [baseline, setBaseline] = useState(JSON.stringify(EMPTY_FORM));
    const [creating, setCreating] = useState(false); const [editing, setEditing] = useState(false); const [deletedMode, setDeletedMode] = useState(false);
    const [mutating, setMutating] = useState(false); const [documents, setDocuments] = useState<ParentSaveDocumentDraftState>(EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE); const [documentError, setDocumentError] = useState<DocumentAggregateDraftError | null>(null);
    const busy = loading || mutating; const dirty = JSON.stringify(form) !== baseline || documents.dirty;

    const load = useCallback(async (keepId?: string) => { const detail = await loadCatalog(config, deletedMode, keepId); const next = formOf(detail, config.parentField); setForm(next); setBaseline(JSON.stringify(next)); return detail; }, [config, deletedMode, loadCatalog]);

    useEffect(() => { resetCatalog(); setCreating(false); setEditing(false); setDocuments(EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE); void load(); return resetCatalog; }, [load, resetCatalog]);
    useEffect(() => { const listener = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", listener); return () => window.removeEventListener("beforeunload", listener); }, [dirty]);

    const select = async (row: CatalogItem) => { if (busy || (dirty && !window.confirm(t("centralCatalog.discard", { defaultValue: "تغییرات ذخیره‌نشده نادیده گرفته شود؟" })))) return; const detail = await selectCatalog(config, row.id); if (!detail) return; const next = formOf(detail, config.parentField); setForm(next); setBaseline(JSON.stringify(next)); setCreating(false); setEditing(false); setDocuments(EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE); };
    const change = (key: keyof CatalogForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
    const startCreate = () => { clearSelection(); setCreating(true); setEditing(true); const next = { ...EMPTY_FORM }; setForm(next); setBaseline(JSON.stringify(next)); setDocuments(EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE); setDocumentError(null); };
    const save = async () => { if (!form.title.trim() || (creating && !form.code.trim())) return setError(t("centralCatalog.required", { defaultValue: "کد و عنوان الزامی هستند." })); if (form.validFrom && form.validTo && form.validFrom > form.validTo) return setError(t("centralCatalog.dateRange", { defaultValue: "بازه اعتبار نامعتبر است." })); if (!documents.ready || documents.invalid || documents.uploading) return setError(t("centralCatalog.documentsNotReady", { defaultValue: "پیش‌نویس اسناد آماده ذخیره نیست." })); setMutating(true); setError(null); setDocumentError(null); try { let id: string; if (creating) { const body: Record<string, unknown> = { code: form.code.trim().toUpperCase(), title: form.title.trim(), description: form.description.trim() || null, validFrom: form.validFrom || null, validTo: form.validTo || null, documents: toDocumentAggregateRequest(documents) }; if (config.hasSortOrder) body.sortOrder = Number(form.sortOrder || 0); if (config.parentField) body[config.parentField] = form.parentId || null; const result = await centralCatalogApi.create(config, body as never); id = result.entityId; } else { if (!selected) return; const result = await centralCatalogApi.update(config, selected.id, { title: form.title.trim(), description: form.description.trim() || null, validFrom: form.validFrom || null, validTo: form.validTo || null, version: selected.version, documents: toDocumentAggregateRequest(documents) }); id = result.entityId; } clearSelection(); setCreating(false); setEditing(false); setDocuments(EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE); await load(id); } catch (cause) { setDocumentError(toDocumentAggregateDraftError(cause)); setError(cause instanceof Error ? cause.message : String(cause)); } finally { setMutating(false); } };
    const lifecycle = async (action: "activate" | "inactivate" | "delete" | "restore", row = selected) => { if (!row) return; setMutating(true); setError(null); try { await centralCatalogApi.lifecycle(config, row.id, action, row.version); clearSelection(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setMutating(false); } };
    const move = async () => { if (!selected || !config.parentField) return; setMutating(true); setError(null); try { await centralCatalogApi.move(config, selected.id, { [config.parentField]: form.parentId || null, sortOrder: Number(form.sortOrder || 0), version: selected.version }); clearSelection(); await load(selected.id); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setMutating(false); } };

    return <section className="centralCatalogPage">
        <header className="centralCatalogHeader"><Title level="H3">{t(config.titleKey, { defaultValue: config.title })}</Title><div className="centralCatalogActions"><Button design="Emphasized" disabled={busy || deletedMode} onClick={startCreate}>{t("common.create", { defaultValue: "ایجاد" })}</Button><Button disabled={busy} onClick={() => setDeletedMode((value) => !value)}>{deletedMode ? t("common.back", { defaultValue: "بازگشت" }) : t("centralCatalog.deleted", { defaultValue: "حذف‌شده‌ها" })}</Button></div></header>
        {configs.length > 1 && <nav className="centralCatalogKinds">{configs.map((entry) => <Button key={entry.kind} design={entry.kind === kind ? "Emphasized" : "Transparent"} disabled={busy} onClick={() => setKind(entry.kind)}>{t(entry.titleKey, { defaultValue: entry.title })}</Button>)}</nav>}
        {error && <MessageStrip design="Negative" onClose={() => setError(null)}>{error}</MessageStrip>}
        <div className="centralCatalogColumns"><div className="centralCatalogList"><table><thead><tr><th>{t("common.code", { defaultValue: "کد" })}</th><th>{t("common.title", { defaultValue: "عنوان" })}</th><th>{t("common.status", { defaultValue: "وضعیت" })}</th><th>{t("common.actions", { defaultValue: "عملیات" })}</th></tr></thead><tbody>{items.map((row) => <tr key={row.id} className={selected?.id === row.id ? "selected" : ""}><td><button type="button" onClick={() => void select(row)}>{row.code}</button></td><td>{row.title}</td><td>{row.status}</td><td>{deletedMode ? <Button disabled={busy} onClick={() => void lifecycle("restore", row)}>{t("common.restore", { defaultValue: "بازیابی" })}</Button> : <Button design="Transparent" disabled={busy} onClick={() => void select(row)}>{t("common.view", { defaultValue: "مشاهده" })}</Button>}</td></tr>)}</tbody></table>{!busy && items.length === 0 && <p>{t("common.noData", { defaultValue: "داده‌ای وجود ندارد." })}</p>}</div>
        <div className="centralCatalogObject">{(creating || selected) ? <><div className="centralCatalogObjectActions">{selected && !editing && <Button design="Emphasized" onClick={() => setEditing(true)}>{t("common.edit", { defaultValue: "ویرایش" })}</Button>}{editing && <Button design="Emphasized" disabled={busy || !dirty} onClick={() => void save()}>{t("common.save", { defaultValue: "ذخیره" })}</Button>}{selected && !editing && selected.status === "ACTIVE" && <Button onClick={() => void lifecycle("inactivate")}>{t("common.inactivate", { defaultValue: "غیرفعال" })}</Button>}{selected && !editing && selected.status === "INACTIVE" && <Button onClick={() => void lifecycle("activate")}>{t("common.activate", { defaultValue: "فعال" })}</Button>}{selected && !editing && <Button design="Negative" onClick={() => void lifecycle("delete")}>{t("common.delete", { defaultValue: "حذف" })}</Button>}</div>
        <div className="centralCatalogForm"><label>{t("common.code", { defaultValue: "کد" })}<Input value={form.code} readonly={!creating} disabled={busy} onInput={(event) => change("code", valueOf(event))} /></label><label>{t("common.title", { defaultValue: "عنوان" })}<Input value={form.title} readonly={!editing} disabled={busy} onInput={(event) => change("title", valueOf(event))} /></label>{config.parentField && <label>{t("centralCatalog.parent", { defaultValue: "والد / مالک" })}<select value={form.parentId} disabled={!editing || busy} onChange={(event) => change("parentId", event.target.value)}><option value="">{t("centralCatalog.noParent", { defaultValue: "بدون والد" })}</option>{parents.filter((row) => row.id !== selected?.id).map((row) => <option key={row.id} value={row.id}>{row.code} - {row.title}</option>)}</select></label>}{config.hasSortOrder && <label>{t("centralCatalog.sortOrder", { defaultValue: "ترتیب نمایش" })}<Input type="Number" value={form.sortOrder} readonly={!editing} disabled={busy} onInput={(event) => change("sortOrder", valueOf(event))} /></label>}<label>{t("centralCatalog.validFrom", { defaultValue: "اعتبار از" })}<input type="date" value={form.validFrom} disabled={!editing || busy} onChange={(event) => change("validFrom", event.target.value)} /></label><label>{t("centralCatalog.validTo", { defaultValue: "اعتبار تا" })}<input type="date" value={form.validTo} disabled={!editing || busy} onChange={(event) => change("validTo", event.target.value)} /></label><label className="wide">{t("common.description", { defaultValue: "شرح" })}<TextArea rows={5} value={form.description} readonly={!editing} disabled={busy} onInput={(event) => change("description", valueOf(event))} /></label></div>
        {selected && config.supportsMove && editing && <Button disabled={busy} onClick={() => void move()}>{t("centralCatalog.savePlacement", { defaultValue: "ذخیره جابه‌جایی" })}</Button>}
        <DocumentManager targetType={config.documentTarget} targetId={selected?.id ?? null} readOnly={!editing} showActions={editing} busy={busy} persistenceMode="PARENT_SAVE" aggregateError={documentError} onDraftStateChange={(draft) => { setDocuments(draft); setDocumentError(null); }} title={t("centralCatalog.documents", { defaultValue: "اسناد" })} saveFirstMessage={t("document.parentSaveHint", { defaultValue: "فایل‌ها به‌صورت موقت بارگذاری می‌شوند و با ذخیره فرم نهایی خواهند شد." })} />
        {config.kind === "policies" && selected && <PolicyVersionPanel policyId={selected.id} />}
        </> : <MessageStrip design="Information" hideCloseButton>{t("centralCatalog.selectPrompt", { defaultValue: "یک مورد را انتخاب کنید یا مورد جدیدی بسازید." })}</MessageStrip>}</div></div>
    </section>;
}
