import { useCallback, useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button, MessageStrip, TextArea, Title } from "@ui5/webcomponents-react";
import { DocumentManager, EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE, toDocumentAggregateDraftError, toDocumentAggregateRequest, type DocumentAggregateDraftError, type ParentSaveDocumentDraftState } from "@/features/document";
import { httpClient } from "@/shared/infra/http.client";
import type { CatalogMutationResponse, RevisionMutationResponse } from "../domain/centralCatalog.model";

interface PolicyVersion { id: string; policyId: string; versionNumber: number; content?: string | null; versionStatus: "DRAFT" | "PUBLISHED" | "SUPERSEDED"; publishedAt?: string | null; status: "ACTIVE" | "DELETED"; validFrom?: string | null; validTo?: string | null; version: number; }
const emptyDocuments = () => ({ ...EMPTY_PARENT_SAVE_DOCUMENT_DRAFT_STATE });

export default function PolicyVersionPanel({ policyId }: { policyId: string }) {
    const { t } = useTranslation(); const [versions, setVersions] = useState<PolicyVersion[]>([]); const [selected, setSelected] = useState<PolicyVersion | null>(null);
    const [content, setContent] = useState(""); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState(false); const [deletedMode, setDeletedMode] = useState(false); const [documents, setDocuments] = useState<ParentSaveDocumentDraftState>(emptyDocuments());
    const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [documentError, setDocumentError] = useState<DocumentAggregateDraftError | null>(null); const generation = useRef(0);
    const load = useCallback(async (keepId?: string) => { const request = ++generation.current; setBusy(true); try { const rows = await httpClient.get<PolicyVersion[]>(`/api/master-data/central/policies/${policyId}/versions${deletedMode ? "/deleted" : ""}`); if (request !== generation.current) return; setVersions(rows); const next = rows.find((row) => row.id === keepId) ?? rows[0] ?? null; setSelected(next); setContent(next?.content ?? ""); setEditing(false); setCreating(false); setDocuments(emptyDocuments()); } catch (cause) { if (request === generation.current) setError(cause instanceof Error ? cause.message : String(cause)); } finally { if (request === generation.current) setBusy(false); } }, [deletedMode, policyId]);
    useEffect(() => { void load(); return () => { generation.current += 1; }; }, [load]);
    const select = (version: PolicyVersion) => { setSelected(version); setContent(version.content ?? ""); setCreating(false); setEditing(false); setDocuments(emptyDocuments()); };
    const save = async () => { if (!documents.ready || documents.invalid || documents.uploading) return setError(t("centralCatalog.documentsNotReady", { defaultValue: "پیش‌نویس اسناد آماده ذخیره نیست." })); setBusy(true); setDocumentError(null); try { let result: CatalogMutationResponse; if (creating) result = await httpClient.post<CatalogMutationResponse>(`/api/master-data/central/policies/${policyId}/versions`, { content: content.trim() || null, validFrom: null, validTo: null, documents: toDocumentAggregateRequest(documents) }); else { if (!selected) return; result = await httpClient.patch<CatalogMutationResponse>(`/api/master-data/central/policy-versions/${selected.id}`, { content: content.trim() || null, validFrom: selected.validFrom ?? null, validTo: selected.validTo ?? null, version: selected.version, documents: toDocumentAggregateRequest(documents) }); } generation.current += 1; await load(result.entityId); } catch (cause) { setDocumentError(toDocumentAggregateDraftError(cause)); setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
    const publish = async () => { if (!selected) return; setBusy(true); try { await httpClient.post<RevisionMutationResponse>(`/api/master-data/central/policy-versions/${selected.id}/publish`, { version: selected.version }); generation.current += 1; await load(selected.id); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
    const lifecycle = async (action: "delete" | "restore") => { if (!selected) return; setBusy(true); try { await httpClient.post<RevisionMutationResponse>(`/api/master-data/central/policy-versions/${selected.id}/${action}`, { version: selected.version }); generation.current += 1; await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
    const immutable = deletedMode || selected?.versionStatus !== "DRAFT";
    return <section className="policyVersions"><header><Title level="H4">{t("centralCatalog.policyVersions", { defaultValue: "نسخه‌های خط‌مشی" })}</Title><Button disabled={busy || deletedMode} onClick={() => { setCreating(true); setEditing(true); setSelected(null); setContent(""); setDocuments(emptyDocuments()); }}>{t("centralCatalog.newDraft", { defaultValue: "پیش‌نویس جدید" })}</Button><Button disabled={busy} onClick={() => setDeletedMode((value) => !value)}>{deletedMode ? t("common.back", { defaultValue: "بازگشت" }) : t("centralCatalog.deleted", { defaultValue: "حذف‌شده‌ها" })}</Button></header>{error && <MessageStrip design="Negative" onClose={() => setError(null)}>{error}</MessageStrip>}<div className="policyVersionGrid"><aside>{versions.map((version) => <button key={version.id} type="button" className={selected?.id === version.id ? "selected" : ""} onClick={() => select(version)}>v{version.versionNumber} — {t(`centralCatalog.versionStatus.${version.versionStatus}`, { defaultValue: version.versionStatus })}</button>)}</aside><div>{(creating || selected) ? <><div className="centralCatalogObjectActions">{selected && !immutable && !editing && <Button onClick={() => setEditing(true)}>{t("common.edit", { defaultValue: "ویرایش" })}</Button>}{editing && <Button design="Emphasized" disabled={busy} onClick={() => void save()}>{t("common.save", { defaultValue: "ذخیره" })}</Button>}{selected && !immutable && !editing && <Button design="Emphasized" disabled={busy || !selected.content?.trim()} onClick={() => void publish()}>{t("centralCatalog.publish", { defaultValue: "انتشار" })}</Button>}{selected && !deletedMode && selected.versionStatus === "DRAFT" && !editing && <Button design="Negative" disabled={busy} onClick={() => void lifecycle("delete")}>{t("common.delete", { defaultValue: "حذف" })}</Button>}{selected && deletedMode && <Button disabled={busy} onClick={() => void lifecycle("restore")}>{t("common.restore", { defaultValue: "بازیابی" })}</Button>}</div><TextArea rows={9} value={content} readonly={!editing || immutable} disabled={busy} onInput={(event) => setContent((event.target as { value?: string }).value ?? "")} /><DocumentManager targetType="CENTRAL_POLICY_VERSION" targetId={selected?.id ?? null} readOnly={!editing || immutable} showActions={editing && !immutable} busy={busy} persistenceMode="PARENT_SAVE" aggregateError={documentError} onDraftStateChange={(draft) => { setDocuments(draft); setDocumentError(null); }} title={t("centralCatalog.versionDocuments", { defaultValue: "اسناد نسخه" })} /></> : <MessageStrip design="Information" hideCloseButton>{t("centralCatalog.noVersions", { defaultValue: "نسخه‌ای وجود ندارد." })}</MessageStrip>}</div></div></section>;
}
