create table objective (
    id raw(16) not null,
    code varchar2(64 byte) not null,
    name varchar2(255 char) not null,
    description clob,
    objective_type varchar2(64 byte),
    parent_objective_id raw(16),
    valid_from date,
    valid_to date,
    status varchar2(32 byte) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    created_by raw(16) not null,
    updated_by raw(16) not null,
    deleted_at timestamp(6) with time zone,
    deleted_by raw(16),
    version number(19,0) default 0 not null,
    constraint pk_objective primary key (id),
    constraint uk_objective_code unique (code),
    constraint fk_objective_parent foreign key (parent_objective_id) references objective(id),
    constraint ck_objective_code check (code = upper(trim(code))),
    constraint ck_objective_status check (status in ('ACTIVE', 'INACTIVE', 'DELETED')),
    constraint ck_objective_range check (valid_to is null or valid_from is null or valid_from <= valid_to),
    constraint ck_objective_self check (parent_objective_id is null or parent_objective_id <> id),
    constraint ck_objective_deleted check (
        (status = 'DELETED' and deleted_at is not null and deleted_by is not null)
        or (status <> 'DELETED' and deleted_at is null and deleted_by is null))
);

create index ix_objective_parent on objective(parent_objective_id);

create table organization_objective (
    id raw(16) not null,
    organization_id raw(16) not null,
    objective_id raw(16) not null,
    name varchar2(255 char) not null,
    description clob,
    owner varchar2(255 char),
    valid_from date,
    valid_to date,
    status varchar2(32 byte) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    created_by raw(16) not null,
    updated_by raw(16) not null,
    deleted_at timestamp(6) with time zone,
    deleted_by raw(16),
    version number(19,0) default 0 not null,
    constraint pk_organization_objective primary key (id),
    constraint uk_organization_objective unique (organization_id, objective_id),
    constraint fk_organization_objective_org foreign key (organization_id) references organization(id),
    constraint fk_organization_objective_obj foreign key (objective_id) references objective(id),
    constraint ck_organization_objective_status check (status in ('ACTIVE', 'INACTIVE', 'DELETED')),
    constraint ck_organization_objective_range check (valid_to is null or valid_from is null or valid_from <= valid_to),
    constraint ck_organization_objective_deleted check (
        (status = 'DELETED' and deleted_at is not null and deleted_by is not null)
        or (status <> 'DELETED' and deleted_at is null and deleted_by is null))
);

create index ix_organization_objective_obj on organization_objective(objective_id);

insert into masterdata_hierarchy_guard (hierarchy_key) values ('OBJECTIVE');
-- Historical CENTRAL_POLICY_VERSION revision rows remain valid; new writes use Policy.
alter table masterdata_revision_content drop constraint ck_masterdata_revision_content_entity;
alter table masterdata_revision_content add constraint ck_masterdata_revision_content_entity check (entity_type in (
    'ORG',
    'OBJECTIVE',
    'ORGANIZATION_OBJECTIVE',
    'CENTRAL_PROCESS',
    'CENTRAL_SUBPROCESS',
    'CENTRAL_CONTROL',
    'CENTRAL_CONTROL_GROUP',
    'CENTRAL_CONTROL_OBJECTIVE_DEF',
    'CENTRAL_RISK_CATEGORY',
    'CENTRAL_RISK_TEMPLATE',
    'CENTRAL_ACCOUNT_GROUP',
    'CENTRAL_REGULATION_GROUP',
    'CENTRAL_REGULATION',
    'CENTRAL_REQUIREMENT',
    'CENTRAL_POLICY_GROUP',
    'CENTRAL_POLICY',
    'CENTRAL_POLICY_ORG',
    'CENTRAL_POLICY_VERSION',
    'CENTRAL_CONTROL_SCOPE',
    'CENTRAL_RISK_SCOPE',
    'CENTRAL_OBJECTIVE_SCOPE',
    'CENTRAL_REQUIREMENT_SCOPE',
    'CENTRAL_POLICY_SUBPROCESS',
    'CENTRAL_POLICY_CONTROL',
    'CENTRAL_POLICY_REQUIREMENT',
    'CENTRAL_CONTROL_ACCOUNT_GROUP',
    'CENTRAL_OBJECTIVE_ACCOUNT_GROUP',
    'CENTRAL_RISK_CONTROL_COV',
    'CENTRAL_RISK_OBJECTIVE_COV',
    'CENTRAL_CONTROL_OBJECTIVE_COV',
    'CENTRAL_REQUIREMENT_CONTROL_COV',
    'LOCAL_CONTEXT',
    'LOCAL_CONTROL_SCOPE',
    'LOCAL_RISK_SCOPE',
    'LOCAL_OBJECTIVE_SCOPE',
    'LOCAL_REQUIREMENT_SCOPE',
    'LOCAL_RISK_CONTROL_COV',
    'LOCAL_RISK_OBJECTIVE_COV',
    'LOCAL_CONTROL_OBJECTIVE_COV',
    'LOCAL_REQUIREMENT_CONTROL_COV',
    'LOCAL_POLICY_ORG',
    'LOCAL_POLICY_SUBPROCESS',
    'LOCAL_POLICY_CONTROL',
    'LOCAL_POLICY_REQUIREMENT',
    'DOCUMENT',
    'DOCUMENT_VERSION',
    'DOCUMENT_LINK'
));


alter table document_link drop constraint ck_document_link_target_type;
alter table document_link add constraint ck_document_link_target_type check (target_type in (
        'ORG',
        'OBJECTIVE',
        'CENTRAL_PROCESS',
        'CENTRAL_SUBPROCESS',
        'CENTRAL_CONTROL',
        'CENTRAL_CONTROL_OBJECTIVE_DEF',
        'CENTRAL_RISK_CATEGORY',
        'CENTRAL_RISK_TEMPLATE',
        'CENTRAL_ACCOUNT_GROUP',
        'CENTRAL_REGULATION_GROUP',
        'CENTRAL_REGULATION',
        'CENTRAL_REQUIREMENT',
        'CENTRAL_POLICY_GROUP',
        'CENTRAL_POLICY',
        'CENTRAL_POLICY_ORG',
        'CENTRAL_CONTROL_SCOPE',
        'CENTRAL_RISK_SCOPE',
        'CENTRAL_OBJECTIVE_SCOPE',
        'CENTRAL_REQUIREMENT_SCOPE',
        'CENTRAL_POLICY_SUBPROCESS',
        'CENTRAL_POLICY_CONTROL',
        'CENTRAL_POLICY_REQUIREMENT',
        'CENTRAL_CONTROL_ACCOUNT_GROUP',
        'CENTRAL_OBJECTIVE_ACCOUNT_GROUP',
        'CENTRAL_RISK_CONTROL_COV',
        'CENTRAL_RISK_OBJECTIVE_COV',
        'CENTRAL_CONTROL_OBJECTIVE_COV',
        'CENTRAL_REQUIREMENT_CONTROL_COV',
        'LOCAL_CONTEXT',
        'LOCAL_CONTROL_SCOPE',
        'LOCAL_RISK_SCOPE',
        'LOCAL_OBJECTIVE_SCOPE',
        'LOCAL_REQUIREMENT_SCOPE',
        'LOCAL_RISK_CONTROL_COV',
        'LOCAL_RISK_OBJECTIVE_COV',
        'LOCAL_CONTROL_OBJECTIVE_COV',
        'LOCAL_REQUIREMENT_CONTROL_COV',
        'LOCAL_POLICY_ORG',
        'LOCAL_POLICY_SUBPROCESS',
        'LOCAL_POLICY_CONTROL',
        'LOCAL_POLICY_REQUIREMENT',
        'MASTERDATA_REVISION'
    ));
