package com.digiaudit.grcpc.modules.usermanagement.domain.enums;

public enum BusinessPermissionCode {
    ORGANIZATION_VIEW,
    ORGANIZATION_CREATE,
    ORGANIZATION_EDIT,
    ORGANIZATION_DELETE,
    REGULATION_VIEW,
    REGULATION_EDIT,
    PROCESS_VIEW,
    PROCESS_EDIT,
    CONTROL_VIEW,
    CONTROL_EDIT,
    RISK_VIEW,
    RISK_EDIT,
    OBJECTIVE_VIEW,
    OBJECTIVE_EDIT,
    POLICY_VIEW,
    POLICY_EDIT,
    ACCOUNT_GROUP_VIEW,
    ACCOUNT_GROUP_EDIT,
    DOCUMENT_VIEW,
    DOCUMENT_UPLOAD,
    DOCUMENT_DOWNLOAD,
    DOCUMENT_DELETE,
    ACL_MANAGE
}
