package com.digiaudit.grcpc.modules.audit.domain.enums;

public enum AuditTargetType {
    SYSTEM_SETUP,
    USER,
    ROLE,
    DELEGATION_POLICY,
    PROCESS,
    CONTROL,
    RISK,
    OBJECTIVE,
    POLICY,
    REGULATION,
    ACCOUNT_GROUP,
    ORGANIZATION_PROCESS_ASSIGNMENT,
    PROCESS_OBJECTIVE_ASSIGNMENT,
    ORGANIZATION_RISK_ASSIGNMENT,
    ORGANIZATION_REFERENCE_ASSIGNMENT,
    DOCUMENT,
    RESOURCE_ACL
}
