package com.digiaudit.grcpc.modules.audit.domain.enums;

public enum AuditEventType {
    SYSTEM_INITIALIZED,
    ROOT_USER_CREATED,
    USER_CREATED,
    USER_UPDATED,
    USER_ROLE_ASSIGNED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_PERMISSION_REPLACED,
    ROLE_BUSINESS_PERMISSION_REPLACED,
    DELEGATION_POLICY_CREATED,
    DELEGATION_POLICY_UPDATED,
    ACCESS_DENIED,
    PRIVILEGE_ESCALATION_BLOCKED
}
