package com.digiaudit.grcpc.modules.document.application;

import com.digiaudit.grcpc.modules.document.domain.DocumentLinkTargetType;

final class DocumentCatalogPermissions {
  private DocumentCatalogPermissions() {}

  static String view(DocumentLinkTargetType type) {
    return switch (type) {
      case ORGANIZATION -> "MD_REFERENCE_VIEW";
      case CENTRAL_PROCESS, CENTRAL_SUBPROCESS -> "MD_PROCESS_VIEW";
      case CENTRAL_CONTROL -> "MD_CONTROL_VIEW";
      case CENTRAL_CONTROL_OBJECTIVE -> "MD_CONTROL_VIEW";
      case CENTRAL_RISK_CATEGORY, CENTRAL_RISK_TEMPLATE -> "MD_RISK_VIEW";
      case CENTRAL_ACCOUNT_GROUP -> "MD_REFERENCE_VIEW";
      case CENTRAL_REGULATION_GROUP, CENTRAL_REGULATION, CENTRAL_REGULATION_REQUIREMENT ->
          "MD_GOVERNANCE_VIEW";
      case CENTRAL_POLICY_GROUP, CENTRAL_POLICY, CENTRAL_POLICY_VERSION -> "MD_GOVERNANCE_VIEW";
      case CENTRAL_SUBPROCESS_CONTROL_SCOPE,
              CENTRAL_SUBPROCESS_RISK_SCOPE,
              CENTRAL_SUBPROCESS_CONTROL_OBJECTIVE_SCOPE,
              CENTRAL_SUBPROCESS_REQUIREMENT_SCOPE,
              CENTRAL_POLICY_VERSION_SUBPROCESS_SCOPE,
              CENTRAL_POLICY_VERSION_CONTROL_SCOPE,
              CENTRAL_POLICY_VERSION_REQUIREMENT_SCOPE,
              CENTRAL_CONTROL_ACCOUNT_GROUP,
              CENTRAL_CONTROL_OBJECTIVE_ACCOUNT_GROUP,
              CENTRAL_SUBPROCESS_RISK_CONTROL_COVERAGE,
              CENTRAL_SUBPROCESS_RISK_CONTROL_OBJECTIVE_COVERAGE,
              CENTRAL_SUBPROCESS_CONTROL_CONTROL_OBJECTIVE_COVERAGE,
              CENTRAL_SUBPROCESS_REQUIREMENT_CONTROL_COVERAGE,
              LOCAL_ORGANIZATION_SUBPROCESS_SCOPE,
              LOCAL_SUBPROCESS_CONTROL_SCOPE,
              LOCAL_SUBPROCESS_RISK_SCOPE,
              LOCAL_SUBPROCESS_CONTROL_OBJECTIVE_SCOPE,
              LOCAL_SUBPROCESS_REQUIREMENT_SCOPE,
              LOCAL_SUBPROCESS_RISK_CONTROL_COVERAGE,
              LOCAL_SUBPROCESS_RISK_CONTROL_OBJECTIVE_COVERAGE,
              LOCAL_SUBPROCESS_CONTROL_CONTROL_OBJECTIVE_COVERAGE,
              LOCAL_SUBPROCESS_REQUIREMENT_CONTROL_COVERAGE,
              LOCAL_POLICY_ORGANIZATION_SCOPE,
              LOCAL_POLICY_SUBPROCESS_SCOPE,
              LOCAL_POLICY_CONTROL_SCOPE,
              LOCAL_POLICY_REQUIREMENT_SCOPE ->
          throw targetNotAvailable();
      case MASTERDATA_REVISION ->
          throw DocumentFailures.invalid(
              "TARGET_NOT_ALLOWED", "Document link target type is not allowed");
    };
  }

  static String mutate(DocumentLinkTargetType type) {
    return switch (type) {
      case ORGANIZATION -> "MD_REFERENCE_MANAGE";
      case CENTRAL_PROCESS, CENTRAL_SUBPROCESS -> "MD_PROCESS_MANAGE";
      case CENTRAL_CONTROL -> "MD_CONTROL_MANAGE";
      case CENTRAL_CONTROL_OBJECTIVE -> "MD_CONTROL_MANAGE";
      case CENTRAL_RISK_CATEGORY, CENTRAL_RISK_TEMPLATE -> "MD_RISK_MANAGE";
      case CENTRAL_ACCOUNT_GROUP -> "MD_REFERENCE_MANAGE";
      case CENTRAL_REGULATION_GROUP, CENTRAL_REGULATION, CENTRAL_REGULATION_REQUIREMENT ->
          "MD_GOVERNANCE_MANAGE";
      case CENTRAL_POLICY_GROUP, CENTRAL_POLICY, CENTRAL_POLICY_VERSION -> "MD_GOVERNANCE_MANAGE";
      case CENTRAL_SUBPROCESS_CONTROL_SCOPE,
              CENTRAL_SUBPROCESS_RISK_SCOPE,
              CENTRAL_SUBPROCESS_CONTROL_OBJECTIVE_SCOPE,
              CENTRAL_SUBPROCESS_REQUIREMENT_SCOPE,
              CENTRAL_POLICY_VERSION_SUBPROCESS_SCOPE,
              CENTRAL_POLICY_VERSION_CONTROL_SCOPE,
              CENTRAL_POLICY_VERSION_REQUIREMENT_SCOPE,
              CENTRAL_CONTROL_ACCOUNT_GROUP,
              CENTRAL_CONTROL_OBJECTIVE_ACCOUNT_GROUP,
              CENTRAL_SUBPROCESS_RISK_CONTROL_COVERAGE,
              CENTRAL_SUBPROCESS_RISK_CONTROL_OBJECTIVE_COVERAGE,
              CENTRAL_SUBPROCESS_CONTROL_CONTROL_OBJECTIVE_COVERAGE,
              CENTRAL_SUBPROCESS_REQUIREMENT_CONTROL_COVERAGE,
              LOCAL_ORGANIZATION_SUBPROCESS_SCOPE,
              LOCAL_SUBPROCESS_CONTROL_SCOPE,
              LOCAL_SUBPROCESS_RISK_SCOPE,
              LOCAL_SUBPROCESS_CONTROL_OBJECTIVE_SCOPE,
              LOCAL_SUBPROCESS_REQUIREMENT_SCOPE,
              LOCAL_SUBPROCESS_RISK_CONTROL_COVERAGE,
              LOCAL_SUBPROCESS_RISK_CONTROL_OBJECTIVE_COVERAGE,
              LOCAL_SUBPROCESS_CONTROL_CONTROL_OBJECTIVE_COVERAGE,
              LOCAL_SUBPROCESS_REQUIREMENT_CONTROL_COVERAGE,
              LOCAL_POLICY_ORGANIZATION_SCOPE,
              LOCAL_POLICY_SUBPROCESS_SCOPE,
              LOCAL_POLICY_CONTROL_SCOPE,
              LOCAL_POLICY_REQUIREMENT_SCOPE ->
          throw targetNotAvailable();
      case MASTERDATA_REVISION ->
          throw DocumentFailures.invalid(
              "TARGET_NOT_ALLOWED", "Document link target type is not allowed");
    };
  }

  private static RuntimeException targetNotAvailable() {
    return DocumentFailures.invalid(
        "TARGET_NOT_AVAILABLE", "Document target runtime is not available yet");
  }
}
