import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button, Dialog, Label, MessageStrip } from "@ui5/webcomponents-react";
import { ModalDialogHeader } from "@/shared/components/ModalDialogHeader";
import { PersianDatePicker, type PersianDateDraftState } from "@/shared/components/PersianDatePicker";
import type { ClassificationDraftRow } from "../domain/controlAccountGroup.model";

const VALID: PersianDateDraftState = { draftValue: "", valid: true, dirty: false };
export default function ClassificationValidityDialog({ open, row, busy, onClose, onSave }: { open: boolean; row: ClassificationDraftRow | null; busy: boolean; onClose: () => void; onSave: (from: string | null, to: string | null) => void }) {
  const { t } = useTranslation(); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [drafts, setDrafts] = useState({ from: VALID, to: VALID }); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!open || !row) return; const timer = window.setTimeout(() => { setFrom(row.validFrom ?? ""); setTo(row.validTo ?? ""); setDrafts({ from: VALID, to: VALID }); setError(null); }, 0); return () => window.clearTimeout(timer); }, [open, row]);
  const save = () => { if (!drafts.from.valid || !drafts.to.valid || (from && to && from > to)) { setError(t("controlAccountGroup.validation.invalidRange")); return; } onSave(from || null, to || null); };
  return <Dialog open={open} accessibleName={t("controlAccountGroup.editor.title")} className="controlAccountGroupDialog" onClose={onClose}><ModalDialogHeader title={t("controlAccountGroup.editor.title")} onClose={onClose} /><div className="controlAccountGroupDialogBody">{error ? <MessageStrip design="Negative" onClose={() => setError(null)}>{error}</MessageStrip> : null}<strong>{row ? `${row.accountGroupCode} — ${row.accountGroupTitle}` : ""}</strong><div className="controlAccountGroupEditorGrid"><div><Label showColon>{t("controlAccountGroup.fields.validFrom")}</Label><PersianDatePicker value={from} disabled={busy} accessibleName={t("controlAccountGroup.fields.validFrom")} invalidValueMessage={t("controlAccountGroup.validation.invalidDate")} onChange={setFrom} onDraftStateChange={(next) => setDrafts((current) => ({ ...current, from: next }))} /></div><div><Label showColon>{t("controlAccountGroup.fields.validTo")}</Label><PersianDatePicker value={to} disabled={busy} accessibleName={t("controlAccountGroup.fields.validTo")} invalidValueMessage={t("controlAccountGroup.validation.invalidDate")} onChange={setTo} onDraftStateChange={(next) => setDrafts((current) => ({ ...current, to: next }))} /></div></div><div className="controlAccountGroupDialogFooter"><Button design="Emphasized" disabled={busy} onClick={save}>{t("controlAccountGroup.actions.apply")}</Button><Button design="Transparent" disabled={busy} onClick={onClose}>{t("common.cancel")}</Button></div></div></Dialog>;
}
