import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { ActionSheet, BusyIndicator, Button, Icon, Input, Label, Link, MessageStrip, ObjectStatus, Option, Select, Table, TableCell, TableHeaderCell, TableHeaderRow, TableRow, Title } from "@ui5/webcomponents-react";
import { formatPersianDate } from "@/shared/utils/date.utils";
import type { AccountGroupOption, ClassificationDraftRow, ClassificationDraftState, ControlAccountGroupChange, ControlAccountGroupClassification } from "../domain/controlAccountGroup.model";
import { controlAccountGroupApi } from "../infra/controlAccountGroup.api";
import { useClassificationDestinationPermissions, useControlAccountGroupPermissions } from "../security/controlAccountGroupPermissions";
import { controlAccountGroupErrorMessage } from "../utils/controlAccountGroupError";
import AccountGroupSelectionDialog from "./AccountGroupSelectionDialog";
import ClassificationValidityDialog from "./ClassificationValidityDialog";
import "../control-account-group.css";

interface Props { controlId: string | null; readOnly: boolean; busy?: boolean; onDraftStateChange?: (state: ClassificationDraftState) => void; }
function flatten(nodes: AccountGroupOption[]): AccountGroupOption[] { return nodes.flatMap((node) => [node, ...flatten(node.children)]); }
function persisted(row: ControlAccountGroupClassification): ClassificationDraftRow { return { key: row.classificationId, classificationId: row.classificationId, accountGroupId: row.accountGroupId, accountGroupCode: row.accountGroupCode, accountGroupTitle: row.accountGroupTitle, parentAccountGroupId: row.parentAccountGroupId, accountGroupStatus: row.accountGroupStatus, status: row.status === "INACTIVE" ? "INACTIVE" : "ACTIVE", validFrom: row.validFrom, validTo: row.validTo, version: row.version, editState: "FINAL", original: row }; }
function same(row: ClassificationDraftRow, original: ControlAccountGroupClassification) { return row.validFrom === original.validFrom && row.validTo === original.validTo && row.status === original.status; }
function changes(rows: ClassificationDraftRow[]): ControlAccountGroupChange[] { return rows.flatMap((row): ControlAccountGroupChange[] => {
  if (row.editState === "DRAFT_DELETE") return [{ operation: "DELETE", accountGroupId: row.accountGroupId, classificationId: row.classificationId, version: row.version }];
  if (!row.original) return [{ operation: "CREATE_OR_RESTORE", accountGroupId: row.accountGroupId, validFrom: row.validFrom, validTo: row.validTo }];
  if (row.editState !== "DRAFT_EDITED") return [];
  const fields = row.validFrom !== row.original.validFrom || row.validTo !== row.original.validTo;
  return fields ? [{ operation: "UPDATE", accountGroupId: row.accountGroupId, classificationId: row.classificationId, version: row.version, validFrom: row.validFrom, validTo: row.validTo, requestedStatus: row.status }]
    : [{ operation: row.status === "ACTIVE" ? "ACTIVATE" : "INACTIVATE", accountGroupId: row.accountGroupId, classificationId: row.classificationId, version: row.version }];
}); }
function opener(event: unknown): HTMLElement | null { const value = (event as { currentTarget?: EventTarget | null }).currentTarget; return value instanceof HTMLElement ? value : null; }

export default function ControlAccountGroupsTab({ controlId, readOnly, busy: parentBusy = false, onDraftStateChange }: Props) {
  const { t } = useTranslation(); const permissions = useControlAccountGroupPermissions(); const destinations = useClassificationDestinationPermissions();
  const [rows, setRows] = useState<ClassificationDraftRow[]>([]); const [options, setOptions] = useState<AccountGroupOption[]>([]);
  const [loading, setLoading] = useState(true); const [loaded, setLoaded] = useState(false); const [error, setError] = useState<string | null>(null); const [search, setSearch] = useState(""); const [filter, setFilter] = useState<"ALL" | "ACTIVE" | "INACTIVE">("ALL");
  const [selectOpen, setSelectOpen] = useState(false); const [editKey, setEditKey] = useState<string | null>(null); const [actionKey, setActionKey] = useState<string | null>(null); const [actionOpener, setActionOpener] = useState<HTMLElement | null>(null); const generation = useRef(0);
  const load = useCallback(async (signal?: AbortSignal) => { const current = ++generation.current; if (!permissions.view) { setRows([]); setOptions([]); setLoading(false); setLoaded(true); return; } setLoading(true); setLoaded(false); try { const [optionResponse, canonical] = await Promise.all([controlAccountGroupApi.options(signal), controlId ? controlAccountGroupApi.forControl(controlId, signal) : Promise.resolve([])]); if (current !== generation.current) return; setOptions(optionResponse.accountGroups); setRows(canonical.map(persisted)); setError(null); setLoaded(true); } catch (cause) { if (cause instanceof Error && cause.name === "AbortError") return; if (current === generation.current) setError(controlAccountGroupErrorMessage(cause, t)); } finally { if (current === generation.current) setLoading(false); } }, [controlId, permissions.view, t]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const pending = useMemo(() => changes(rows), [rows]);
  useEffect(() => onDraftStateChange?.({ changes: pending, dirty: pending.length > 0, ready: loaded || !permissions.view, invalid: Boolean(error) }), [error, loaded, onDraftStateChange, pending, permissions.view]);
  const allOptions = useMemo(() => flatten(options), [options]); const visible = useMemo(() => { const needle = search.trim().toLocaleLowerCase(); return rows.filter((row) => (filter === "ALL" || row.status === filter) && (!needle || row.accountGroupCode.toLocaleLowerCase().includes(needle) || row.accountGroupTitle.toLocaleLowerCase().includes(needle))); }, [filter, rows, search]);
  const editing = rows.find((row) => row.key === editKey) ?? null; const action = rows.find((row) => row.key === actionKey) ?? null; const mutationBusy = parentBusy || loading;
  const confirmSelection = (selected: Set<string>) => { setRows((current) => { const optionById = new Map(allOptions.map((item) => [item.id, item])); const next = current.flatMap((row) => selected.has(row.accountGroupId) ? [{ ...row, editState: row.editState === "DRAFT_DELETE" && row.original ? "FINAL" as const : row.editState }] : row.original ? [{ ...row, editState: "DRAFT_DELETE" as const }] : []); const occupied = new Set(current.map((row) => row.accountGroupId)); for (const id of selected) { if (occupied.has(id)) continue; const item = optionById.get(id); if (item?.status !== "ACTIVE") continue; next.push({ key: `new:${id}`, classificationId: null, accountGroupId: id, accountGroupCode: item.code, accountGroupTitle: item.title, parentAccountGroupId: item.parentAccountGroupId, accountGroupStatus: item.status, status: "ACTIVE", validFrom: null, validTo: null, version: null, editState: "DRAFT_NEW", original: null }); } return next; }); setSelectOpen(false); };
  const saveValidity = (from: string | null, to: string | null) => { if (!editKey) return; setRows((current) => current.map((row) => { if (row.key !== editKey) return row; const next = { ...row, validFrom: from, validTo: to }; return { ...next, editState: !next.original ? "DRAFT_NEW" : same(next, next.original) ? "FINAL" : "DRAFT_EDITED" }; })); setEditKey(null); };
  const setLifecycle = (row: ClassificationDraftRow, status: "ACTIVE" | "INACTIVE") => setRows((current) => current.map((candidate) => candidate.key !== row.key ? candidate : { ...candidate, status, editState: candidate.original && same({ ...candidate, status }, candidate.original) ? "FINAL" : candidate.original ? "DRAFT_EDITED" : "DRAFT_NEW" }));
  const remove = (row: ClassificationDraftRow) => setRows((current) => row.original ? current.map((candidate) => candidate.key === row.key ? { ...candidate, editState: "DRAFT_DELETE" } : candidate) : current.filter((candidate) => candidate.key !== row.key));
  const undo = (row: ClassificationDraftRow) => setRows((current) => row.original ? current.map((candidate) => candidate.key === row.key ? persisted(row.original!) : candidate) : current.filter((candidate) => candidate.key !== row.key));
  const closeActions = () => { setActionKey(null); setActionOpener(null); }; const run = (fn: () => void) => { closeActions(); fn(); };
  const status = (row: ClassificationDraftRow) => row.editState === "FINAL" ? t(`controlAccountGroup.status.${row.status}`) : t(`controlAccountGroup.editState.${row.editState}`);
  if (!permissions.view) return <MessageStrip design="Information">{t("controlAccountGroup.errors.forbidden")}</MessageStrip>;
  return <section className="controlAccountGroupTab"><div className="controlAccountGroupToolbar"><Title level="H5">{t("controlAccountGroup.title")}</Title><div className="controlAccountGroupToolbarGroup"><Input className="controlAccountGroupSearch" value={search} placeholder={t("controlAccountGroup.search")} disabled={mutationBusy} onInput={(event) => setSearch(event.target.value)} /><div><Label showColon>{t("controlAccountGroup.fields.status")}</Label><Select value={filter} disabled={mutationBusy} onChange={(event) => setFilter(event.target.value as typeof filter)}><Option value="ALL">{t("controlAccountGroup.filter.all")}</Option><Option value="ACTIVE">{t("controlAccountGroup.status.ACTIVE")}</Option><Option value="INACTIVE">{t("controlAccountGroup.status.INACTIVE")}</Option></Select></div>{!readOnly && (permissions.create || permissions.lifecycle || permissions.restore || permissions.delete) ? <Button design="Emphasized" disabled={mutationBusy || !loaded} onClick={() => setSelectOpen(true)}>{t("controlAccountGroup.actions.select")}</Button> : null}</div></div>
    {error ? <MessageStrip design="Negative" onClose={() => setError(null)}>{error}<Button design="Transparent" onClick={() => void load()}>{t("controlAccountGroup.actions.retry")}</Button></MessageStrip> : null}
    {loading ? <BusyIndicator active delay={0} /> : visible.length ? <Table headerRow={<TableHeaderRow><TableHeaderCell>{t("controlAccountGroup.fields.accountGroup")}</TableHeaderCell><TableHeaderCell>{t("controlAccountGroup.fields.validFrom")}</TableHeaderCell><TableHeaderCell>{t("controlAccountGroup.fields.validTo")}</TableHeaderCell><TableHeaderCell>{t("controlAccountGroup.fields.status")}</TableHeaderCell>{!readOnly ? <TableHeaderCell>{t("common.actions")}</TableHeaderCell> : null}</TableHeaderRow>}>{visible.map((row) => <TableRow key={row.key} rowKey={row.key}><TableCell>{destinations.accountGroupView ? <Link href="/account-groups" wrappingType="Normal">{`${row.accountGroupCode} — ${row.accountGroupTitle}`}</Link> : `${row.accountGroupCode} — ${row.accountGroupTitle}`}</TableCell><TableCell>{formatPersianDate(row.validFrom)}</TableCell><TableCell>{formatPersianDate(row.validTo)}</TableCell><TableCell><ObjectStatus state={row.editState === "FINAL" && row.status === "ACTIVE" ? "Positive" : row.editState === "FINAL" ? "None" : "Information"} icon={<Icon name={row.editState === "FINAL" && row.status === "ACTIVE" ? "accept" : row.editState === "FINAL" ? "pause" : "information"} mode="Decorative" />}>{status(row)}</ObjectStatus></TableCell>{!readOnly ? <TableCell><Button design="Transparent" icon="overflow" accessibleName={t("common.actions")} disabled={mutationBusy} onClick={(event) => { setActionKey(row.key); setActionOpener(opener(event)); }} /></TableCell> : null}</TableRow>)}</Table> : loaded ? <div className="controlAccountGroupEmpty">{t("controlAccountGroup.empty")}</div> : null}
    {!readOnly ? <ActionSheet open={Boolean(action && actionOpener)} opener={actionOpener} placement="Bottom" horizontalAlign="End" headerText={t("common.actions")} onClose={closeActions}>{action && action.editState !== "FINAL" ? <Button icon="undo" onClick={() => run(() => undo(action))}>{t("controlAccountGroup.actions.undo")}</Button> : <>{action && permissions.update ? <Button icon="edit" onClick={() => run(() => setEditKey(action.key))}>{t("controlAccountGroup.actions.edit")}</Button> : null}{action && permissions.lifecycle && action.status === "ACTIVE" ? <Button icon="pause" onClick={() => run(() => setLifecycle(action, "INACTIVE"))}>{t("controlAccountGroup.actions.inactivate")}</Button> : null}{action && permissions.lifecycle && action.status === "INACTIVE" ? <Button icon="accept" onClick={() => run(() => setLifecycle(action, "ACTIVE"))}>{t("controlAccountGroup.actions.activate")}</Button> : null}{action && permissions.delete ? <Button icon="delete" onClick={() => run(() => remove(action))}>{t("controlAccountGroup.actions.delete")}</Button> : null}</>}</ActionSheet> : null}
    <AccountGroupSelectionDialog open={selectOpen} options={options} rows={rows} busy={mutationBusy} canSelect={permissions.create || permissions.lifecycle || permissions.restore} canDelete={permissions.delete} onClose={() => setSelectOpen(false)} onConfirm={confirmSelection} />
    <ClassificationValidityDialog open={Boolean(editing)} row={editing} busy={mutationBusy} onClose={() => setEditKey(null)} onSave={saveValidity} />
  </section>;
}
