import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { BusyIndicator, Link, MessageStrip, ObjectStatus, Table, TableCell, TableHeaderCell, TableHeaderRow, TableRow, Title } from "@ui5/webcomponents-react";
import type { DerivedSubprocessAccountGroup } from "../domain/controlAccountGroup.model";
import { controlAccountGroupApi } from "../infra/controlAccountGroup.api";
import { useClassificationDestinationPermissions, useControlAccountGroupPermissions } from "../security/controlAccountGroupPermissions";
import { controlAccountGroupErrorMessage } from "../utils/controlAccountGroupError";
import "../control-account-group.css";

export default function SubprocessAccountGroupsTab({ subprocessId, allowNestedNavigation = true }: { subprocessId: string; allowNestedNavigation?: boolean }) {
  const { t } = useTranslation(); const permissions = useControlAccountGroupPermissions(); const destinations = useClassificationDestinationPermissions(); const [rows, setRows] = useState<DerivedSubprocessAccountGroup[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); if (!permissions.view) return () => controller.abort(); void controlAccountGroupApi.forSubprocess(subprocessId, controller.signal).then(setRows).catch((cause) => { if (!(cause instanceof Error && cause.name === "AbortError")) setError(controlAccountGroupErrorMessage(cause, t)); }).finally(() => setLoading(false)); return () => controller.abort(); }, [permissions.view, subprocessId, t]);
  if (!permissions.view) return <MessageStrip design="Information">{t("controlAccountGroup.errors.forbidden")}</MessageStrip>;
  return <section className="controlAccountGroupTab"><Title level="H5">{t("controlAccountGroup.derived.title")}</Title>{error ? <MessageStrip design="Negative">{error}</MessageStrip> : null}{loading ? <BusyIndicator active delay={0} /> : rows.length ? <Table headerRow={<TableHeaderRow><TableHeaderCell>{t("controlAccountGroup.fields.accountGroup")}</TableHeaderCell><TableHeaderCell>{t("controlAccountGroup.derived.accountGroupStatus")}</TableHeaderCell><TableHeaderCell>{t("controlAccountGroup.derived.contributingControls")}</TableHeaderCell></TableHeaderRow>}>{rows.map((row) => <TableRow key={row.accountGroupId} rowKey={row.accountGroupId}><TableCell>{allowNestedNavigation && destinations.accountGroupView ? <Link href="/account-groups" wrappingType="Normal">{`${row.accountGroupCode} — ${row.accountGroupTitle}`}</Link> : `${row.accountGroupCode} — ${row.accountGroupTitle}`}</TableCell><TableCell><ObjectStatus state={row.accountGroupStatus === "ACTIVE" ? "Positive" : row.accountGroupStatus === "INACTIVE" ? "None" : "Negative"}>{t(`controlAccountGroup.accountGroupStatus.${row.accountGroupStatus}`)}</ObjectStatus></TableCell><TableCell><div className="controlAccountGroupContributionList">{row.contributingControls.map((source) => <span key={source.classificationId}>{allowNestedNavigation && destinations.controlView ? <Link href="/controls" wrappingType="Normal">{`${source.controlCode} — ${source.controlTitle}`}</Link> : `${source.controlCode} — ${source.controlTitle}`} <ObjectStatus state={source.controlScopeStatus === "ACTIVE" && source.classificationStatus === "ACTIVE" ? "Positive" : "None"}>{t("controlAccountGroup.derived.sourceStatus", { scope: t(`controlAccountGroup.status.${source.controlScopeStatus}`), classification: t(`controlAccountGroup.status.${source.classificationStatus}`) })}</ObjectStatus></span>)}</div></TableCell></TableRow>)}</Table> : <div className="controlAccountGroupEmpty">{t("controlAccountGroup.derived.empty")}</div>}</section>;
}
